/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vitv.presentationeditor;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.GridBagLayout;
import java.awt.Point;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.MouseListener;
import javax.swing.JDesktopPane;
import javax.swing.JScrollPane;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import javax.swing.JViewport;

/**
 *
 * @author kpliuniverse
 */
public final class MainApp extends javax.swing.JFrame {
    void addInFrame() {
        // Assuming desktopPane is already defined
        JInternalFrame internalFrame = new JInternalFrame("Test Frame", true, true, true, true);
        internalFrame.setSize(300, 200);
        internalFrame.setVisible(true);
        internalFrame.setMaximizable(false);
        internalFrame.setLayer(LayerConsts.INTERNAL_FRAME_LAYER);
        workSpace.add(internalFrame); // Add to JDesktopPane
        internalFrame.setLocation(50, 50); // Set initial position
        //workSpace.setDesktopManager(new javax.swing.DefaultDesktopManager()); // Ensure DesktopManager is active

    }
    
    
    private JPanel canvasPaneViewport, subCPV;
    private JPanel curCanvas;
    
    void initCanvasPanel() {
        
        canvasPaneViewport = new JPanel();
        canvasPaneViewport.setLayout(new GridBagLayout());
        subCPV = new JPanel();
        subCPV.setLayout(new FlowLayout());
        canvasPaneViewport.add(subCPV);
       
        
    }
    void createCanvas() {
        
        curCanvas = CurCanvas.getInstance().panel;
        curCanvas.setVisible(true);
        subCPV.add(curCanvas, BorderLayout.CENTER);
        // Create a JPanel to hold a list of labels.

      
        
    }
    
    void makeCanvasInFrameUndraggable() {
        for(MouseListener listener : ((javax.swing.plaf.basic.BasicInternalFrameUI) this.canvasInFrame.getUI()).getNorthPane().getMouseListeners()){
            javax.swing.plaf.basic.BasicInternalFrameUI t = ((javax.swing.plaf.basic.BasicInternalFrameUI) this.canvasInFrame.getUI());
            t.getNorthPane().removeMouseListener(listener);
            
            //t.getSouthPane().removeMouseListener(listener);
            //t.getEastPane().removeMouseListener(listener);
            //t.getWestPane().removeMouseListener(listener);
        }
        javax.swing.plaf.basic.BasicInternalFrameUI x = ((javax.swing.plaf.basic.BasicInternalFrameUI) this.canvasInFrame.getUI());
        x.setNorthPane(null); x.setSouthPane(null); x.setEastPane(null); x.setWestPane(null);
    }
    /**
     * Creates new form MainApp
     */
    
    // Store the last known width and divider position
    private int lastWidth;
    public MainApp() {
        initComponents();
        lastWidth = mainSP.getWidth();
        addInFrame();
        this.makeCanvasInFrameUndraggable();
        toolBar.setFloatable(false);
        canvasInFrame.setLayout(new BorderLayout());
        createCanvas();
        canvasInFrame.remove(canvasPane);
        canvasInFrame.add(canvasPane, BorderLayout.CENTER);
        mainSP.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                float ratio = (float) mainSP.getDividerLocation() / (float) lastWidth;
                
                int newWidth = mainSP.getWidth();
                mainSP.setDividerLocation((int) (newWidth * ratio));
                lastWidth = newWidth;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        workSpace = new javax.swing.JDesktopPane() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(Color.decode("#B3B3B3"));
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        mainSP = new javax.swing.JSplitPane();
        canvasInFrame = new javax.swing.JInternalFrame();

        canvasInFrame.setBackground(Color.decode("#555555"));
        canvasInFrame.setOpaque(true);
        this.initCanvasPanel();
        canvasPane = new JScrollPane(canvasPaneViewport);

        canvasPane.getViewport().setBackground(ColorConsts.WORKSPACE_BG);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolBar.setBackground(new java.awt.Color(204, 204, 255));
        toolBar.setRollover(true);

        workSpace.setBackground(new java.awt.Color(179, 179, 179));
        workSpace.setDesktopManager(new javax.swing.DefaultDesktopManager());

        mainSP.setDividerLocation(700);

        canvasInFrame.setBackground(new java.awt.Color(85, 85, 85));
        canvasInFrame.setBorder(null);
        canvasInFrame.setEnabled(false);
        canvasInFrame.setVisible(true);

        canvasPane.setBackground(new java.awt.Color(85, 85, 85));
        canvasPane.setBorder(null);

        javax.swing.GroupLayout canvasInFrameLayout = new javax.swing.GroupLayout(canvasInFrame.getContentPane());
        canvasInFrame.getContentPane().setLayout(canvasInFrameLayout);
        canvasInFrameLayout.setHorizontalGroup(
            canvasInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, canvasInFrameLayout.createSequentialGroup()
                .addComponent(canvasPane, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addContainerGap())
        );
        canvasInFrameLayout.setVerticalGroup(
            canvasInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvasPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        mainSP.setLeftComponent(canvasInFrame);

        workSpace.setLayer(mainSP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout workSpaceLayout = new javax.swing.GroupLayout(workSpace);
        workSpace.setLayout(workSpaceLayout);
        workSpaceLayout.setHorizontalGroup(
            workSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSP)
        );
        workSpaceLayout.setVerticalGroup(
            workSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSP)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(workSpace)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workSpace))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame canvasInFrame;
    private javax.swing.JScrollPane canvasPane;
    private javax.swing.JSplitPane mainSP;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JDesktopPane workSpace;
    // End of variables declaration//GEN-END:variables
}
