/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vitv.presentationeditor;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author kpliuniverse
 */
public final class MainApp extends javax.swing.JFrame {
    void addExFrame() {
        // Assuming desktopPane is already defined
        JInternalFrame internalFrame = new JInternalFrame("Test Frame", true, true, true, true);
        internalFrame.setSize(300, 200);
        internalFrame.setVisible(true);
        internalFrame.setMaximizable(false);
        workSpace.add(internalFrame); // Add to JDesktopPane
        internalFrame.setLocation(50, 50); // Set initial position
        //workSpace.setDesktopManager(new javax.swing.DefaultDesktopManager()); // Ensure DesktopManager is active

    }
    
    void createCanvas() {
        
        JPanel canvPanel = CurCanvas.getInstance().panel;
        canvPanel.setVisible(true);
        canvasPane.add(canvPanel);
        
    }
    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
        addExFrame();
        toolBar.setFloatable(false);
        canvasPane.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workSpace = new javax.swing.JDesktopPane() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(Color.decode("#B3B3B3"));
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        canvasInFrame = new javax.swing.JInternalFrame();
        canvasPane = new javax.swing.JScrollPane();
        toolBar = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        workSpace.setBackground(new java.awt.Color(179, 179, 179));
        workSpace.setDesktopManager(new javax.swing.DefaultDesktopManager());

        canvasInFrame.setBorder(null);
        canvasInFrame.setVisible(true);

        canvasPane.setBackground(new java.awt.Color(122, 122, 122));

        javax.swing.GroupLayout canvasInFrameLayout = new javax.swing.GroupLayout(canvasInFrame.getContentPane());
        canvasInFrame.getContentPane().setLayout(canvasInFrameLayout);
        canvasInFrameLayout.setHorizontalGroup(
            canvasInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvasPane)
        );
        canvasInFrameLayout.setVerticalGroup(
            canvasInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvasPane, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        workSpace.setLayer(canvasInFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout workSpaceLayout = new javax.swing.GroupLayout(workSpace);
        workSpace.setLayout(workSpaceLayout);
        workSpaceLayout.setHorizontalGroup(
            workSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvasInFrame)
        );
        workSpaceLayout.setVerticalGroup(
            workSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvasInFrame, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        toolBar.setRollover(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workSpace)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workSpace))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame canvasInFrame;
    private javax.swing.JScrollPane canvasPane;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JDesktopPane workSpace;
    // End of variables declaration//GEN-END:variables
}
